keys:

# User Keys

  - &admin age1hzd4wek48s4mpptw00l30uhgpmcm4atuhjnqtxttftnhp8xflgnqxzdhmz # Main PC

# Host Keys

  - &host_andromeda age18wc67zrkjh7n4xe7c2j5pe60yyhqgwrx5jvwnw3jkq74c84r9drsth2stg # Incus Node 1

# Groups

compute: &compute
  - *host_andromeda

creation_rules:
  # Per Host Secrets
  - path_regex: ^hosts[\\/]compute[\\/]andromeda[\\/]secrets\.yaml$
    key_groups:
      - age:
        - *admin
        - *host_andromeda


  # Shared Secrets
  - path_regex: ^secrets[\\/]common\.yaml$
    key_groups:
      - age:
        - *admin
        - *host_andromeda

  - path_regex: ^secrets[\\/]compute\.yaml$
    key_groups:
      - age:
        - *admin
        - *host_andromeda

  - path_regex: ^secrets[\\/]edge\.yaml$
    key_groups:
      - age:
        - *admin

  - path_regex: ^secrets[\\/]standalone\.yaml$
    key_groups:
      - age:
        - *admin

  - path_regex: ^secrets[\\/]storage\.yaml$
    key_groups:
      - age:
        - *admin

  - path_regex: ^secrets[\\/]virtual\.yaml$
    key_groups:
      - age:
        - *admin