{ config, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix   # generated by `nixos-generate-config`
    ../../modules/base.nix
    ../../modules/home.nix
    ../../modules/users.nix
    ../../modules/networking.nix
    ../../modules/services.nix
  ];

  networking.hostName = "homelab-server";

  system.stateVersion = "25.11";
}